### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by JanaDrieschner** [JanaDrieschner/capstone-picky-eaters#12]
Value Proposition

As a User
I want to navigate through pages 
so that I am able to move between pages 
​

## Description

​

## Acceptance Criteria

- [ ] a fixed navbar is visible at the bottom of the page 
- [ ] navbar leads leads to different pages 

      ​

## Tasks

- [ ] Create a navigation component 
- [ ] add navigation component to every page 
- [ ] add links for pages
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by lenzloesche** [comment]
some suggestions:
- either delete complexity or write a value.
- _navbar leads leads to different pages_
did you mean:
_links lead to different pages_ ?
- maybe add if you want to have text-links or image-links for your navbar.
