### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by JanaDrieschner** [JanaDrieschner/capstone-picky-eaters#17]
Value Proposition

As a User
I want to use the app on every device 
so that my data is saved 
​

​
Acceptance Criteria

- [ ] create a database connection
- [ ] use CRUD 

      ​

## Tasks

- [ ] use mongoDB atlas
- [ ] create collections for forms, adding recipes and random recipes

      ​

## Complexity

... (T-Shirt Sizes XS to XL)
