### ISSUE TITLE
own Recipes detail page

### ISSUE THREAD

**Issue by JanaDrieschner** [JanaDrieschner/capstone-picky-eaters#22]
Value Proposition

As a User
I want to see a recipes video or have the option to get to the original website
so that I can watch a Video or go to the website
​

Description

![detail own](https://user-images.githubusercontent.com/123373466/227951383-cc1ae597-8bb9-43d0-ad02-ea51b1fcb516.png)

​

Acceptance Criteria

- [ ] inputfield for the Video?
- [ ] button/link to the website
- [ ] inputfield for personal notes

      ​

## Tasks

- [ ] checkout React-Player
- [ ] checkout cloudinary

      ​

## Complexity

... (T-Shirt Sizes XS to XL)
