### ISSUE TITLE
User experience

### ISSUE THREAD

**Issue by JanaDrieschner** [JanaDrieschner/capstone-picky-eaters#24]
## Value Proposition

As a Developer
I want to to improve the user experience of my app
so that the user has a simple and intuitive experience when using the app

## Description

deleting all unnecessary links 
making sure of mobile first design​

## Acceptance Criteria

- [ ] no dead buttons/links
- [ ] articles and sections are designed mobile first

## Tasks

- [ ] delete "favorite" svg in navigation, you don't need it yet
- [ ] delete "url" link, you don't need it yet
- [ ] make sure all StyledContainer are mobile first 
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by alinawinter** [comment]
Looks good, makes absolute sense for the user :-) 
(I don't understand, what is written under "Complexity" though?)
