### ISSUE TITLE
Adding random recipes

### ISSUE THREAD

**Issue by JanaDrieschner** [JanaDrieschner/capstone-picky-eaters#30]
## Value Proposition

As a User
I want to add recipes to a List
so that I have an overview of all my recipes 
​

## Description

Icon which leads to the page "my recipes
​

## Acceptance Criteria

- [ ] add icon -> + to details page of random recipes 
- [ ] all recipes (my own and random ones) are listed on "my recipes" page 
- [ ] later you can think about favorites
- [ ] later you can think about a searchbar
- [ ] later you can think about food categories
      ​
## Tasks

- [ ] icon/link is placed on detailspage of random recipes -> routing
    
## Complexity

s
