### ISSUE TITLE
Food categories for Recipe List 

### ISSUE THREAD

**Issue by JanaDrieschner** [JanaDrieschner/capstone-picky-eaters#33]
## Value Proposition

As a User
I want to be able to organize recipes into different categories such as "Breakfast", "Lunch" and so on 
so that I can filter the recipe list based on the categories/tags I'm interested in
​

## Description

- Dropdown menu with categories on Homepage?
​
## Acceptance Criteria

- [ ] should be able to save alle the incoming recipes -> from the api and your own 

## Tasks

- [ ] Dropdownmenu on Homepage 
- [ ] Searchbar/Dropdownmenu for My Recipes
- [ ] localstorage

## Complexity

L

**Comment by rabe200** [comment]
acceptance criteria seems to be to precise. no technical terms (localstorage) here. keep it more general. for example "save recipe". the details can go to your dev notes -> tasks :)

**Comment by JanaDrieschner** [comment]
thank you, just edited ist

**Comment by rabe200** [comment]
the acceptance ain't clear to me. can you be more precise what the coder has to do here? coders aren't philosopher.
